name: Tests
on:
  - push
  - pull_request
jobs:
  tests:
    runs-on: "${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - { python-version: "3.13", os: ubuntu-latest, session: "pre-commit" }
          - { python-version: "3.10", os: ubuntu-latest, session: "tests" }
          - { python-version: "3.11", os: ubuntu-latest, session: "tests" }
          - { python-version: "3.12", os: ubuntu-latest, session: "tests" }
          - { python-version: "3.13", os: ubuntu-latest, session: "tests" }
          - { python-version: "3.11", os: macos-latest, session: "tests" }
          - { python-version: "3.12", os: macos-latest, session: "tests" }
          - { python-version: "3.13", os: macos-latest, session: "tests" }
          - { python-version: "3.10", os: windows-latest, session: "tests" }
          - { python-version: "3.11", os: windows-latest, session: "tests" }
          - { python-version: "3.12", os: windows-latest, session: "tests" }
          - { python-version: "3.13", os: windows-latest, session: "tests" }

    name: "${{ matrix.session }} ${{ matrix.python-version }} / ${{ matrix.os }}"
    env:
      NOXSESSION: "${{ matrix.session }}"
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Compute pre-commit cache key
      if: matrix.session == 'pre-commit'
      id: pre-commit-cache
      shell: python
      run: |
        import hashlib
        import sys
        import os
        python = "py{}.{}".format(*sys.version_info[:2])
        payload = sys.version.encode() + sys.executable.encode()
        digest = hashlib.sha256(payload).hexdigest()
        result = "${{ runner.os }}-{}-{}-pre-commit".format(python, digest[:8])
        with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
            print(f"result={result}", file=f)
    - name: Restore pre-commit cache
      uses: actions/cache@v4
      if: matrix.session == 'pre-commit'
      with:
        path: ~/.cache/pre-commit
        key: "${{ steps.pre-commit-cache.outputs.result }}-${{ hashFiles('.pre-commit-config.yaml') }}"
        restore-keys: |
          "${{ steps.pre-commit-cache.outputs.result }}-"
    - name: Run Nox
      run: |
        uv run --locked --group dev nox --force-color --python=${{ matrix.python-version }}
